### ISSUE TITLE
Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts

### ISSUE THREAD

**Issue by bgits** [loomnetwork/tiles-chain-evm#3]
The above error gets thrown in the console when setting a tile with v1.7.1. The state is updated but requires a refresh to display the updated state.

Get thrown at this line: https://github.com/loomnetwork/tiles-chain-evm/blob/master/webclient/src/contract_client.js#L39

Could this be an issue with the loom provider itself?

**Comment by mattkanwisher** [comment]
ack, we will put it on our queue

**Comment by eduardonunesp** [comment]
@bgits this example will receive an update soon, it's using an older version of `loom-js`

**Comment by eduardonunesp** [comment]
The example is updated and running :)
